ENT.Base = "npc_vj_human_base"
ENT.Type = "ai"
ENT.PrintName = "Clone Soldier (1.0)"
ENT.Author = "Darkborn"
ENT.Contact = "http://steamcommunity.com/groups/vrejgaming"
ENT.Category = "Paranoia Resurgence"
